openapi: 3.0.3
info:
  title: Athena AI API
  version: 0.1.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.athena.app
security:
  - bearerAuth: []
paths:
  /api/v1/ai/stream:
    get:
      summary: Stream AI response (SSE)
      operationId: aiStream
      parameters:
        - in: query
          name: conversation_id
          schema: { type: string, format: uuid }
        - in: query
          name: prompt
          schema: { type: string }
      responses:
        "200": { description: OK }
        "401": { description: Unauthorized }
  /api/v1/ai/conversations:
    get:
      summary: List conversations
      operationId: listConversations
      responses:
        "200": { description: OK }
        "401": { description: Unauthorized }
    post:
      summary: Create conversation
      operationId: createConversation
      responses:
        "200": { description: OK }
        "401": { description: Unauthorized }
  /api/v1/ai/messages:
    get:
      summary: List messages
      operationId: listMessages
      parameters:
        - in: query
          name: conversation_id
          schema: { type: string, format: uuid }
      responses:
        "200": { description: OK }
        "401": { description: Unauthorized }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer