openapi: 3.0.3
info:
  title: Athena Notes API
  version: 0.1.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.athena.app
paths:
  /api/v1/notes:
    get:
      operationId: listNotes
      summary: List notes with cursor pagination
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
        - in: query
          name: cursor
          schema:
            type: string
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
    post:
      operationId: createNote
      summary: Create note (idempotent)
      security:
        - bearerAuth: []
      parameters:
        - in: header
          name: Idempotency-Key
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [book_id, content]
              properties:
                book_id:
                  type: string
                content:
                  type: string
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
  /api/v1/notes/{note_id}:
    get:
      operationId: getNote
      summary: Get note
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: note_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
    patch:
      operationId: updateNote
      summary: Update note with optimistic concurrency
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: note_id
          required: true
          schema:
            type: string
        - in: header
          name: If-Match
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: OK
        "409":
          description: Version Conflict
    delete:
      operationId: deleteNote
      summary: Soft delete note
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: note_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer