openapi: 3.0.3
info:
  title: Athena Pricing API
  version: 0.1.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.athena.app
security:
  - bearerAuth: []
paths:
  /api/v1/pricing/rules:
    get:
      summary: List pricing rules
      operationId: listPricingRules
      parameters:
        - in: query
          name: service_type
          schema:
            type: string
        - in: query
          name: region
          schema:
            type: string
      responses:
        "200":
          description: OK
        "401": { description: Unauthorized }
  /api/v1/admin/pricing/rules:
    get:
      summary: Admin list pricing rules
      operationId: adminListPricingRules
      responses:
        "200":
          description: OK
        "401": { description: Unauthorized }
    post:
      summary: Admin create pricing rule
      operationId: adminCreatePricingRule
      responses:
        "200":
          description: OK
        "400": { description: Bad Request }
        "401": { description: Unauthorized }
  /api/v1/admin/pricing/rules/{rule_id}:
    patch:
      summary: Admin update pricing rule
      operationId: adminUpdatePricingRule
      parameters:
        - in: path
          name: rule_id
          required: true
          schema: { type: string, format: uuid }
      responses:
        "200":
          description: OK
        "412": { description: ETag Mismatch }
        "401": { description: Unauthorized }
    delete:
      summary: Admin delete pricing rule
      operationId: adminDeletePricingRule
      parameters:
        - in: path
          name: rule_id
          required: true
          schema: { type: string, format: uuid }
      responses:
        "200":
          description: OK
        "401": { description: Unauthorized }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer