openapi: 3.0.3
info:
  title: Athena Profile API
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.athena.app
paths:
  /api/v1/profile/me:
    get:
      operationId: getProfileMe
      summary: 获取当前用户资料
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            ETag:
              description: 资源版本标签
              schema: { type: string }
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
        '401': { description: Unauthorized }
    patch:
      operationId: patchProfileMe
      summary: 更新当前用户资料（乐观并发 + 幂等）
      security:
        - bearerAuth: []
      parameters:
        - in: header
          name: If-Match
          required: true
          schema: { type: string }
        - in: header
          name: Idempotency-Key
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProfileUpdate'
      responses:
        '200':
          description: OK
          headers:
            ETag:
              description: 新版本标签
              schema: { type: string }
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
        '400': { description: INVALID }
        '409': { description: VERSION_CONFLICT }

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Profile:
      type: object
      properties:
        user_id: { type: string, format: uuid }
        display_name: { type: string }
        timezone: { type: string }
        language: { type: string }
        version: { type: integer }
    ProfileUpdate:
      type: object
      properties:
        display_name: { type: string }
        timezone: { type: string }
        language: { type: string }
