openapi: 3.0.3
info:
  title: Athena Shelves API
  version: 0.1.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:8000
paths:
  /api/v1/shelves:
    post:
      summary: 创建书架
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
        "400": { description: Bad Request }
        "401": { description: Unauthorized }
        "409": { description: Conflict }
    get:
      summary: 列出书架
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
        "401": { description: Unauthorized }
  /api/v1/shelves/{shelf_id}:
    patch:
      summary: 更新书架（并发控制）
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: shelf_id
          required: true
          schema:
            type: string
        - in: header
          name: If-Match
          schema:
            type: string
      responses:
        "200":
          description: OK
        "400": { description: Bad Request }
        "401": { description: Unauthorized }
        "404": { description: Not Found }
        "409": { description: Conflict }
  /api/v1/shelves/{shelf_id}/items:
    post:
      summary: 书架添加书籍
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: shelf_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
        "400": { description: Bad Request }
        "401": { description: Unauthorized }
        "404": { description: Not Found }
    get:
      summary: 列出书架书籍
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: shelf_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
        "401": { description: Unauthorized }
  /api/v1/shelves/{shelf_id}/items/{book_id}:
    delete:
      summary: 从书架移除书籍
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: shelf_id
          required: true
          schema:
            type: string
        - in: path
          name: book_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
        "401": { description: Unauthorized }
        "404": { description: Not Found }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer