openapi: 3.0.3
info:
  title: Athena Tags API
  version: 0.1.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.athena.app
paths:
  /api/v1/tags:
    post:
      operationId: createTag
      summary: 创建标签
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
        "400": { description: Bad Request }
        "401": { description: Unauthorized }
        "409": { description: Conflict }
    get:
      operationId: listTags
      summary: 列出标签
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
        "401": { description: Unauthorized }
  /api/v1/tags/{tag_id}:
    patch:
      operationId: updateTag
      summary: 更新标签（并发控制）
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: tag_id
          required: true
          schema:
            type: string
        - in: header
          name: If-Match
          schema:
            type: string
      responses:
        "200":
          description: OK
        "400": { description: Bad Request }
        "401": { description: Unauthorized }
        "404": { description: Not Found }
        "409": { description: Conflict }
    delete:
      operationId: deleteTag
      summary: 删除标签
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: tag_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
        "401": { description: Unauthorized }
        "404": { description: Not Found }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer