openapi: 3.0.3
info:
  title: Athena TTS API
  version: 0.1.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.athena.app
security:
  - bearerAuth: []
paths:
  /api/v1/tts:
    post:
      summary: Generate TTS and return download url
      operationId: ttsGenerate
      responses:
        "200": { description: OK }
        "401": { description: Unauthorized }
  /api/v1/tts/heartbeat:
    post:
      summary: Accumulate TTS duration
      operationId: ttsHeartbeat
      responses:
        "200": { description: OK }
        "401": { description: Unauthorized }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer